version: '3'
services:
  react-animations:
    image: henriquemazzoleni/react-animations
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles